blogApp/urls.py
from django.urls import path
from . import views

app_name = 'blogApp'

urlpatterns = [
    path('', views.home, name='home'),
    path('articles/', views.articles, name='articles'),
    # path('article/', views.article, name='article'),
    path('<slug:article>/', views.article, name='article'),


]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # import blogApp.urls
    path('', include('blogApp.urls', namespace='blogApp')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogApp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    profile_pic = models.ImageField(null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    twitter = models.URLField(max_length=200, null=True, blank=True)

    def __str__(self):
        name = str(self.first_name)
        if self.last_name:
            name += ' ' + str(self.last_name)
        return name

class ArticleManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')

class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Article(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='author')

    headline = models.CharField(max_length=200)
    sub_headline = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to='article', default='placeholder.png')
    body = RichTextUploadingField(null=True, blank=True)
    featured = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name='tags', blank=True)

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    slug = models.SlugField(max_length=200, unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10, choices=options, default='draft')

    objects = models.Manager()
    articlemanager = ArticleManager()

    def get_absolute_url(self):
        return reverse('blogApp:article', args=[self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.headline

blogApp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article, Tag, Profile
from django.db.models import Q

# def home(request):
#     return render(request, 'index.html')

def home(request):
    featured = Article.articlemanager.filter(featured=True)[0:3]
    context = {
        'articles': featured
    }
    return render(request, 'index.html', context)

def article(request, article):
    article = get_object_or_404(Article, slug=article, status='published')
    context = {
        'article': article
    }
    return render(request, 'article.html', context)

def articles(request):
    # get query from request
    query = request.GET.get('query')
    if query == None:
        query = ''

    # article = Article.articlemanager.all()
    # search for query in headline, sub_headline, body
    articles = Article.articlemanager.filter(
        Q(headline__icontains=query) |
        Q(sub_headline__icontains=query) |
        Q(body__icontains=query)
    )

    tags = Tag.objects.all()

    context = {
        'articles': articles,
        'tags': tags,
    }

    return render(request, 'articles.html', context)

blogApp/templates/article.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bloggies</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Boxicon awesome icon -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"">
    <style type="text/css">
      img{
        max-width: 100%;
        object-fit: cover;
      }
    
      .featured_image{
        margin-top: 20px;
        margin-bottom: 20px;
      }
    
      .post-container{
          width: 900px;
          margin: 0 auto;
          padding-top: 20px;
          padding-bottom: 20px;
      }
    
      .author-pic{
        width: 50px;
        height: 50px;
        border-radius: 50%;
        margin-right: 10px;
      }
    
      @media screen and (max-width: 900px){
        .post-container{
          width: 95%;
        }
      }
    </style>
    
  </head>
  <body>

    <!-- header -->
    
    <nav class = "navbar">
      <div class = "container">
        <a href = "{% url 'blogApp:home' %}" class = "navbar-brand">Academy.Omen</a>
        <div class = "navbar-nav">
          <a href = "{% url 'blogApp:home' %}">home</a>
          <a href = "{% url 'blogApp:articles' %}">articles</a>
          <a href = "">about</a>
        </div>
      </div>
    </nav>
    
    <!-- end of header -->

    <!-- start of post -->
    <div class="post-container">
        <img class="featured_img" src="{{ article.image.url }}">
        <!-- start article details -->
        <div class="article-info">
          <div class="article-info-content display-center">
            <div class="display-center">
              <img class="author-pic" src="{{ article.author.profile_pic.url }}" alt="">
              <h6>by {{ article.author }} on {{ article.publish|date:"D M Y" }}</h6>
            </div>
            
            <div class="article-meta">
              {% for tag in article.tags.all %}
              <span class="tag"><a href="#">{{ tag.name }}</a></span>
              {% endfor %}
              <a class="back-button" href="{% url 'blogApp:articles' %}">All Articles</a>
            </div>
          </div>
        </div>
        <!-- end of article details -->
        <hr>   
        <h1>headline</h1>
        <h4>sub_headline</h4>
        <br>
        <p>{{ article.body|safe }}</p>
    </div>
    <!-- end of post -->

    <!-- footer -->
    <footer>
      <div class = "social-links">
        <a href = "#"><i class='bx bxl-facebook'></i></a>
        <a href = "#"><i class='bx bxl-twitter'></i></a>
        <a href = "#"><i class='bx bxl-instagram'></i></a>
        <a href = "#"><i class='bx bxl-github'></i></a>
      </div>
      <span>Academy.Omen Bloggies</span>
    </footer>
    <!-- end of footer -->
    
    
  </body>
</html>

blogApp/templates/articles.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bloggies</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Boxicon awesome icon -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"">
    
  </head>
  <body>

    <!-- header -->
    
    <nav class = "navbar">
        <div class = "container">
          <a href = "{% url 'blogApp:home' %}" class = "navbar-brand">Academy.Omen</a>
          <div class = "navbar-nav">
            <a href = "{% url 'blogApp:home' %}">home</a>
            <a href = "{% url 'blogApp:articles' %}">articles</a>
            <a href = "">about</a>
          </div>
        </div>
    </nav>
    
    <!-- end of header -->

    <div class = "container">
        <div class = "title">
          <h2>All Articles</h2>
        </div>
        <form method="GET">
          <input type="text" id="query" name="query" class="textbox" placeholder="Search">
          <button type = "submit" class="button">
            <i class='bx bx-search'></i>
          </button>
        </form>
        <div class="article-meta">
            <a class="back-button" href="{% url 'blogApp:articles' %}">All Articles</a>
            {% for tag in tags %}
            <span class="tag"><a href="#">{{ tag.name }}</a></span>
            {% endfor %}
        </div>

        <hr>

        <div class = "featured-content">
          {% for article in articles %}
          <!-- item -->
          <div class = "featured-item">
            <div class = "featured-img">
              <a href="{{ article.get_absolute_url }}">
                <img src = "{{ article.image.url }}" alt = "">
                <span><i class='bx bx-calendar-star'></i>{{ article.publish|date:"M Y" }}</span>
                <span>{{ article.sub_headline }}</span>
              </a>
            </div>
            <div class = "featured-title">
              <a href = "{{ article.get_absolute_url }}">{{ article.headline }}</a>
            </div>
          </div>
          <!-- end of item -->
          {% empty %}
			      <h3>No Article found...</h3>  
          {% endfor %}
        </div>
    </div>

    <!-- footer -->
    <footer>
      <div class = "social-links">
        <a href = "#"><i class='bx bxl-facebook'></i></a>
        <a href = "#"><i class='bx bxl-twitter'></i></a>
        <a href = "#"><i class='bx bxl-instagram'></i></a>
        <a href = "#"><i class='bx bxl-github'></i></a>
      </div>
      <span>Academy.Omen Bloggies</span>
    </footer>
    <!-- end of footer -->
    
    
  </body>
</html>

blogApp/templates/index.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bloggies</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Boxicon awesome icon -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>

    <!-- header -->
    <header>
      <nav class = "navbar">
        <div class = "container">
          <a href = "{% url 'blogApp:home' %}" class = "navbar-brand">Academy.Omen</a>
          <div class = "navbar-nav">
            <a href = "{% url 'blogApp:home' %}">home</a>
            <a href = "{% url 'blogApp:articles' %}">articles</a>
            <a href = "">about</a>
          </div>
        </div>
      </nav>
      <div class = "banner">
        <div class = "container">
          <h1 class = "banner-title">
            <span>Omen.</span> Bloggies
          </h1>
          <p>everything you need to know about building a Sass with Django</p>
        </div>
      </div>
    </header>
    <!-- end of header -->
    
    <!-- featured -->
    <section class = "featured" id = "featured">
      <div class = "container">
        <div class = "title">
          <h2>Featured articles</h2>
        </div>

        <div class = "featured-content">
          {% for article in articles %}
          <!-- item -->
          <div class = "featured-item">
            <div class = "featured-img">
              <a href="{{ article.get_absolute_url }}">
                <img src = "{{ article.image.url }}" alt = "">
                <span><i class='bx bx-calendar-star'></i>{{ article.publish|date:"M Y" }}</span>
                <span>{{ article.sub_headline }}</span>
              </a>
            </div>
            <div class = "featured-title">
              <a href = "{{ article.get_absolute_url }}">{{ article.headline }}</a>
            </div>
          </div>
          <!-- end of item -->
          {% empty %}
			      <h3>No Featured Article at the Moment...</h3>  
          {% endfor %}
        </div>
      </div>
    </section>
    <!-- end of featured -->

    <!-- about -->
    <section class = "about" id = "about">
      <div class = "container">
        <div class = "about-content">
          <div>
            <img src = "{% static 'images/about.jpg' %}" alt = "">
          </div>
          <div class = "about-text">
            <div class = "title">
              <h2>Catherine Doe</h2>
              <p>art & design is my passion</p>
            </div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id totam voluptatem saepe eius ipsum nam provident sapiente, natus et vel eligendi laboriosam odit eos temporibus impedit veritatis ut, illo deserunt illum voluptate quis beatae quod. Necessitatibus provident dicta consectetur labore!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam corrupti natus, eos quia recusandae voluptatem veniam modi officiis minima provident rem sint porro fuga quos tempora ea suscipit vero velit sed laudantium eaque necessitatibus maxime!</p>
          </div>
        </div>
      </div>
    </section>
    <!-- end of about -->

    <!-- footer -->
    <footer>
      <div class = "social-links">
        <a href = "#"><i class='bx bxl-facebook'></i></a>
        <a href = "#"><i class='bx bxl-twitter'></i></a>
        <a href = "#"><i class='bx bxl-instagram'></i></a>
        <a href = "#"><i class='bx bxl-github'></i></a>
      </div>
      <span>Academy.Omen Bloggies</span>
    </footer>
    <!-- end of footer -->

    
    
  </body>
</html>